<?php

namespace menuBundle\Repository;

/**
 * menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends \Doctrine\ORM\EntityRepository
{
}
